# Site settings
title: "Overwatch Analytics"
email: bellegar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Analyzing Overwatch League games.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffbellegarde.github.io" # the base hostname & protocol for your site
github_username:  JeffBellegarde

# Build settings
markdown: kramdown
exclude: [vendor]
